export default [
  {
    icon: 'UpOutlined',
    id: '200000',
    name: '系统管理',
    pid: '',
    path: '/systemManager',
    permission: '',
  },
  {
    icon: '',
    id: '200100',
    name: '岗位维护',
    pid: '200000',
    path: '/systemManager/jobManager',
    permission: '',
  },
  {
    icon: '',
    id: '200101',
    name: '岗位信息',
    pid: '200100',
    path: '/systemManager/jobManager/jobInfo',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '200102',
    name: '审核信息',
    pid: '200100',
    path: '/systemManager/jobManager/jobVerifyInfo',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '200200',
    name: '用户维护',
    pid: '200000',
    path: '/systemManager/userManager',
    permission: '',
  },
  {
    icon: '',
    id: '200201',
    name: '用户信息',
    pid: '200200',
    path: '/systemManager/userManager/userInfo',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '200202',
    name: '审核信息',
    pid: '200200',
    path: '/systemManager/userManager/userVerifyInfo',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '200300',
    name: '默认密码设置',
    pid: '200000',
    path: '/systemManager/setPassword',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '300000',
    name: '基础信息',
    pid: '',
    path: '/baseInformation',
    permission: '',
  },
  {
    icon: '',
    id: '300100',
    name: '日历维护',
    pid: '300000',
    path: '/baseInformation/calendarMainten',
    permission: '',
  },
  {
    icon: '',
    id: '300101',
    name: '日历维护',
    pid: '300100',
    path: '/baseInformation/calendarMainten/calendarManager',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '300102',
    name: '审核信息',
    pid: '300100',
    path: '/baseInformation/calendarMainten/checkInformation',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '300103',
    name: '日历初始化',
    pid: '300100',
    path: '/baseInformation/calendarMainten/calendarManagerInit',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '300200',
    name: '风控参数设置',
    pid: '300000',
    path: '/baseInformation/riskControlSetup',
    permission: '',
  },
  {
    icon: '',
    id: '300201',
    name: '曲线/曲面构造参数',
    pid: '300200',
    path: '/baseInformation/riskControlSetup/curveParam',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '300202',
    name: '盯市及风险敞口参数',
    pid: '300200',
    path: '/baseInformation/riskControlSetup/riskOpenParam',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '300203',
    name: '场景构建参数',
    pid: '300200',
    path: '/baseInformation/riskControlSetup/sceneConstructParam',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '300300',
    name: '场景维护/导入',
    pid: '300000',
    path: '/baseInformation/sceneMaintainImport',
    permission: '',
  },
  {
    icon: '',
    id: '300301',
    name: '数据导入',
    pid: '300300',
    path: '/baseInformation/sceneMaintainImport/dataImport',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '300302',
    name: '数据审核',
    pid: '300300',
    path: '/baseInformation/sceneMaintainImport/dataCheck',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '400000',
    name: '风险管理',
    pid: '',
    path: '/riskManagement',
    permission: '',
  },
  {
    icon: '',
    id: '400100',
    name: '日终/日初处理',
    pid: '400000',
    path: '/riskManagement/dayStartAndEnd',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '400200',
    name: '现金流监控',
    pid: '400000',
    path: '/riskManagement/cashMonitor',
    permission: '',
  },
  {
    icon: '',
    id: '400201',
    name: '现金流监控',
    pid: '400200',
    path: '/riskManagement/cashMonitor/cashflowMonitoring',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '400202',
    name: '现金流汇总监控',
    pid: '400200',
    path: '/riskManagement/cashMonitor/cashflowMonitoringSummary',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '500000',
    name: '数据查询',
    pid: '',
    path: '/dataQuery',
    permission: '',
  },
  {
    icon: '',
    id: '500100',
    name: '合约要素查询',
    pid: '500000',
    path: '/dataQuery/contractElementQuery',
    permission: '',
  },
  {
    icon: '',
    id: '500101',
    name: '外汇询价交易',
    pid: '500100',
    path: '/dataQuery/contractElementQuery/foreignExchangeTransaction',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '500200',
    name: '场景数据查询',
    pid: '500000',
    path: '/dataQuery/sceneDataQuery',
    permission: '',
  },
  {
    icon: '',
    id: '500201',
    name: '历史场景',
    pid: '500200',
    path: '/dataQuery/sceneDataQuery/historyScene',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '500300',
    name: '盯市风险敞口查询',
    pid: '500000',
    path: '/dataQuery/marketRiskQuery',
    permission: '',
  },
  {
    icon: '',
    id: '500301',
    name: '交易日终/日间估值结果',
    pid: '500300',
    path: '/dataQuery/marketRiskQuery/dayStartAndEndResult',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '500400',
    name: '回溯测试结果查询',
    pid: '500000',
    path: '/dataQuery/backTestQuery',
    permission: '',
  },
  {
    icon: '',
    id: '500401',
    name: '回溯结果',
    pid: '500400',
    path: '/dataQuery/backTestQuery/backResult',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '500500',
    name: '压力测试结果查询',
    pid: '500000',
    path: '/dataQuery/stressTestQuery',
    permission: 'all:admin',
  },
  {
    icon: '',
    id: '600000',
    name: '任务管理',
    pid: '',
    path: '',
    permission: '',
  },
  {
    icon: '',
    id: '600100',
    name: '日志查询',
    pid: '600000',
    path: '/logQuery',
    permission: 'all:admin',
  },
];
